version: '3'
services:  
  phpmyadmin:
        depends_on:
          - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - '8080:80'
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: 1234  
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: testLogin
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
